# Generated by Django 3.1.5 on 2021-05-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('run_empresa', models.CharField(max_length=12)),
                ('fecha_venta', models.DateField()),
                ('monto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('idorden_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_orden', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('fecha_cierre', models.DateField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoFamiliar',
            fields=[
                ('idproductofamiliar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'producto_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_expiracion', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('stock_critico', models.BigIntegerField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('numero_recibo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=10)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('fecha_venta', models.DateField()),
                ('monto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'recibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idreporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField()),
                ('total_ventas', models.BigIntegerField()),
                ('monto_venta', models.BigIntegerField()),
                ('total_visitas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idtipoproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvendedor', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('precio', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('precio_final', models.BigIntegerField()),
                ('metodo_pago', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('delivery', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProductos',
            fields=[
                ('calidad_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('otros_detalles', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'venta_productos',
                'managed': False,
            },
        ),
    ]
